name: Deployment Multi Container
on:
  push:
    branches: # can be more than one setup
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} --password-stdin
      - run: docker build -t ahmadleoyudanto/docker-multi-container-client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ahmadleoyudanto/docker-multi-container-client-test npm test

      - run: docker build -t ahmadleoyudanto/docker-multi-container-client ./client
      - run: docker build -t ahmadleoyudanto/docker-multi-container-nginx ./nginx
      - run: docker build -t ahmadleoyudanto/docker-multi-container-server ./server
      - run: docker build -t ahmadleoyudanto/docker-multi-container-worker ./worker

      - run: docker push ahmadleoyudanto/docker-multi-container-client:latest
      - run: docker push ahmadleoyudanto/docker-multi-container-nginx:latest
      - run: docker push ahmadleoyudanto/docker-multi-container-server:latest
      - run: docker push ahmadleoyudanto/docker-multi-container-worker:latest