name: Deployment Multi Container
on:
  push:
    branches: # can be more than one setup
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t alkinemokiye/docker-multi-container-client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alkinemokiye/docker-multi-container-client-test npm test
      - run: docker build -t alkinemokiye/docker-multi-container-client ./client
      - run: docker build -t alkinemokiye/docker-multi-container-nginx ./nginx
      - run: docker build -t alkinemokiye/docker-multi-container-server ./server
      - run: docker build -t alkinemokiye/docker-multi-container-worker ./worker
      - run: docker push alkinemokiye/docker-multi-container-client
      - run: docker push alkinemokiye/docker-multi-container-nginx
      - run: docker push alkinemokiye/docker-multi-container-server
      - run: docker push alkinemokiye/docker-multi-container-worker